// The gen~ codebox, generated. Every offset comes from layout.ts, so the
// codebox and the v8 script that reads its output cannot disagree; the
// per-sample algorithm is mirrored line for line by reference.ts, which is what
// the tests run. **Change one, change the other.**
//
// What it does, per sample:
//   - passes the audio through untouched (out1/out2 are in1/in2, always first);
//   - publishes Live's sample rate in the stats header, so v8 knows which
//     coefficients to write;
//   - when v8 bumps `coefgen`, copies the coefficient buffer~ (float32 hi/lo
//     pairs) into the 64-bit `Data co`, once;
//   - when v8 bumps `epoch`, zeroes every filter and the block being built and
//     restarts the ring — the start of a listening pass;
//   - only while `listen` is on and the loaded coefficients match the running
//     rate: K-weighting, 4× true peak, peaks/overs/sums, and the 31 bands on
//     (L+R)/2, summed into the current block, which is written to the ring every
//     100 ms. When `listen` falls, the partial block is flushed so the final
//     report includes it.
//
// Not listening costs one comparison and two header writes a sample: a probe
// left in a set does no analysis until something asks it to.

import {
  BAND_COUNT,
  BLOCK_SECONDS,
  CO_BANDS,
  CO_KW,
  CO_SIZE,
  CO_TP,
  F_BANDS,
  F_KL,
  F_KR,
  F_N,
  F_OVERS,
  F_SP,
  F_SUM_L,
  F_SUM_LL,
  F_SUM_LR,
  F_SUM_R,
  F_SUM_RR,
  F_TP,
  H_BLOCK_LEN,
  H_COEF_SR,
  H_EPOCH,
  H_HEAD,
  H_SR,
  HEAD_MOD,
  HEADER,
  SECTIONS,
  CELLS,
  STRIDE,
  TP_FACTOR,
  TP_TAPS,
} from './layout.ts';

/** gen~-private filter state, in `Data st`. reference.ts uses the same layout. */
export const ST_KW = 0; // L shelf s1 s2, L high-pass s1 s2, R shelf, R high-pass
export const ST_BANDS = 8; // BAND_COUNT × SECTIONS × (s1, s2)
export const ST_TP = ST_BANDS + BAND_COUNT * SECTIONS * 2; // two rings of TP_HISTORY inputs
export const TP_HISTORY = TP_TAPS / TP_FACTOR;
export const ST_SIZE = ST_TP + 2 * TP_HISTORY;

/** Names gen~ exposes as attributes/params; the patch addresses them. */
export const GEN_STATS = 'stats';
export const GEN_COEF = 'coef';

/** One transposed direct form II section, coefficients at co[`c`], state at st[`z`]. */
function section(x: string, y: string, c: string, z: string): string {
  return [
    `${y} = peek(co, ${c}) * ${x} + peek(st, ${z});`,
    `poke(st, peek(co, ${c} + 1) * ${x} - peek(co, ${c} + 3) * ${y} + peek(st, ${z} + 1), ${z});`,
    `poke(st, peek(co, ${c} + 2) * ${x} - peek(co, ${c} + 4) * ${y}, ${z} + 1);`,
  ].join('\n');
}

const add = (field: number, expr: string) =>
  `poke(acc, peek(acc, ${field}) + ${expr}, ${field});`;

/** Write the block being built into the ring, advance the head, start a new one. */
const commit = `
poke(acc, blk, ${F_N});
cell_base = ${HEADER} + (head % ${CELLS}) * ${STRIDE};
for (i = 0; i < ${STRIDE}; i = i + 1) {
	poke(stats, peek(acc, i), cell_base + i, 0);
	poke(acc, 0, i);
}
head = (head + 1) % ${HEAD_MOD};
poke(stats, head, ${H_HEAD}, 0);
blk = 0;`;

const indent = (text: string, tabs: number) =>
  text
    .trim()
    .split('\n')
    .map((l) => '\t'.repeat(tabs) + l)
    .join('\n');

export function genCode(): string {
  return `// Generated by tools/build-probe.ts from probe/src/genexpr.ts. Do not edit.
Param listen(0);
Param epoch(0);
Param coefgen(0);
Buffer ${GEN_STATS}("openflow-probe-stats");
Buffer ${GEN_COEF}("openflow-probe-coef");
Data co(${CO_SIZE});
Data st(${ST_SIZE});
Data acc(${STRIDE});
History loaded_gen(-1);
History coef_sr(0);
History cur_epoch(-1);
History blk(0);
History head(0);
History tp_w(0);
History was_listening(0);

out1 = in1;
out2 = in2;

sr_now = samplerate;
block_len = floor(sr_now * ${BLOCK_SECONDS} + 0.5);
poke(stats, sr_now, ${H_SR}, 0);
poke(stats, block_len, ${H_BLOCK_LEN}, 0);

if (coefgen != loaded_gen) {
	for (i = 0; i < ${CO_SIZE}; i = i + 1) {
		poke(co, peek(coef, 2 * i, 0) + peek(coef, 2 * i + 1, 0), i);
	}
	loaded_gen = coefgen;
	coef_sr = peek(co, 0);
	poke(stats, coef_sr, ${H_COEF_SR}, 0);
}

if (epoch != cur_epoch) {
	for (i = 0; i < ${ST_SIZE}; i = i + 1) {
		poke(st, 0, i);
	}
	for (i = 0; i < ${STRIDE}; i = i + 1) {
		poke(acc, 0, i);
	}
	blk = 0;
	head = 0;
	tp_w = 0;
	cur_epoch = epoch;
	poke(stats, 0, ${H_HEAD}, 0);
	poke(stats, epoch, ${H_EPOCH}, 0);
}

if (listen < 0.5 && was_listening > 0.5 && blk > 0) {
${indent(commit, 1)}
}
was_listening = listen;

if (listen > 0.5 && coef_sr == sr_now) {
	x_l = in1;
	x_r = in2;

	// K-weighting, BS.1770: shelf then high-pass, per channel.
${indent(section('x_l', 'k_a', `${CO_KW}`, `${ST_KW}`), 1)}
${indent(section('k_a', 'k_l', `${CO_KW + 5}`, `${ST_KW + 2}`), 1)}
${indent(section('x_r', 'k_b', `${CO_KW}`, `${ST_KW + 4}`), 1)}
${indent(section('k_b', 'k_r', `${CO_KW + 5}`, `${ST_KW + 6}`), 1)}
	${add(F_KL, 'k_l * k_l')}
	${add(F_KR, 'k_r * k_r')}

	// Sample statistics.
	a_l = abs(x_l);
	a_r = abs(x_r);
	s_peak = max(a_l, a_r);
	poke(acc, max(peek(acc, ${F_SP}), s_peak), ${F_SP});
	${add(F_OVERS, '(a_l >= 1) + (a_r >= 1)')}
	${add(F_SUM_L, 'x_l')}
	${add(F_SUM_R, 'x_r')}
	${add(F_SUM_LL, 'x_l * x_l')}
	${add(F_SUM_RR, 'x_r * x_r')}
	${add(F_SUM_LR, 'x_l * x_r')}

	// True peak: ${TP_FACTOR}× polyphase interpolation over the last ${TP_HISTORY} inputs,
	// never below the sample peak.
	poke(st, x_l, ${ST_TP} + tp_w);
	poke(st, x_r, ${ST_TP + TP_HISTORY} + tp_w);
	t_peak = s_peak;
	for (p = 0; p < ${TP_FACTOR}; p = p + 1) {
		y_l = 0;
		y_r = 0;
		for (k = 0; k < ${TP_HISTORY}; k = k + 1) {
			j = (tp_w - k + ${TP_HISTORY}) % ${TP_HISTORY};
			h = peek(co, ${CO_TP} + ${TP_FACTOR} * k + p);
			y_l = y_l + h * peek(st, ${ST_TP} + j);
			y_r = y_r + h * peek(st, ${ST_TP + TP_HISTORY} + j);
		}
		t_peak = max(t_peak, max(abs(y_l), abs(y_r)));
	}
	tp_w = (tp_w + 1) % ${TP_HISTORY};
	poke(acc, max(peek(acc, ${F_TP}), t_peak), ${F_TP});

	// The 31 third-octave bands on the mid signal, ${SECTIONS} sections each.
	mid = (x_l + x_r) * 0.5;
	for (b = 0; b < ${BAND_COUNT}; b = b + 1) {
		y = mid;
		for (s = 0; s < ${SECTIONS}; s = s + 1) {
			c = ${CO_BANDS} + (b * ${SECTIONS} + s) * 5;
			z = ${ST_BANDS} + (b * ${SECTIONS} + s) * 2;
			x = y;
${indent(section('x', 'y', 'c', 'z'), 3)}
		}
		poke(acc, peek(acc, ${F_BANDS} + b) + y * y, ${F_BANDS} + b);
	}

	blk = blk + 1;
	if (blk >= block_len) {
${indent(commit, 2)}
	}
}
`;
}
