#!/usr/bin/env node
// Builds probe/OpenFlowProbe.amxd, probe/OpenFlowProbe.maxpat and probe/probe.js.
// `npm run build:probe`. Generated the way build-device.ts generates
// SessionBridge — nothing here is ever hand-edited in Max.
//
//   [plugin~] ─> [gen~ @stats ---… @coef ---…] ─> [plugout~]      audio, untouched
//                    ▲ params             │ writes 100 ms blocks
//                    │                    ▼
//   [r openflow-probe-in] ─> [v8 probe.js ---… ---…] ─> [s openflow-probe-out]
//                              │   reads blocks, writes coefficients
//                              ├─> [pattr openflow-probe-key]   the stored key
//                              ├─> [bye …(  ◀── [freebang]  ─> [s openflow-probe-out]
//                              └─> status text on the face
//   [live.thisdevice] ─> [t b b b] ─ liveid ← [live.path this_device]
//                                  ─ storedkey ← [pattr]
//                                  ─ loaded
//
// The measuring itself — what each stage computes and why — is in
// probe/README.md and the modules under probe/src.

import esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { pack } from './amxd.ts';
import { GEN_COEF, GEN_STATS, genCode } from '../probe/src/genexpr.ts';
import { COEF_FRAMES, STATS_FRAMES } from '../probe/src/layout.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'probe');

const DEVICE = 'OpenFlowProbe';
const TITLE = 'open[flow] Probe';
const DESCRIPTION =
  'Measures the audio passing through it — loudness, peaks and tonal balance — for open[flow]. ' +
  'The audio is not changed.';

/** The probe↔bridge sends. Global on purpose, no `---`: one bridge hears every probe. */
const PROBE_OUT = 'openflow-probe-out';
const PROBE_IN = 'openflow-probe-in';

/**
 * Per-device buffer~ names. `---` becomes a number unique to this device
 * instance in every object box, so two probes in a set never share a ring.
 */
const STATS_BUF = '---openflow-probe-stats';
const COEF_BUF = '---openflow-probe-coef';

const DEVICE_W = 150;
const DEVICE_H = 169;

// ---------------------------------------------------------------------------
// probe.js — the v8 script
// ---------------------------------------------------------------------------

const bundle = await esbuild.build({
  entryPoints: [path.join(root, 'probe', 'src', 'main.ts')],
  bundle: true,
  write: false,
  format: 'iife',
  globalName: '__probe',
  platform: 'neutral',
  target: 'es2022',
  legalComments: 'none',
  minify: false, // this is what you read in the Max window when it goes wrong
});

/**
 * The plain-script tail. Max's [v8] finds message handlers as top-level
 * function declarations, and Buffer, Dict, Task, outlet and post are its
 * globals — so every Max name lives here, and probe/src never touches one.
 * jsarguments[1] and [2] are the buffer~ names after `---` substitution.
 */
const TAIL = `
// ---- Max glue (generated by tools/build-probe.ts) ----
var autowatch = 0;
var inlets = 1;
var outlets = 5;
var __buffers = {};
function __buffer(name) {
  if (!name) return null;
  if (!__buffers[name]) __buffers[name] = new Buffer(String(name));
  return __buffers[name];
}
var __p = __probe.start({
  statsBuffer: function () { return __buffer(jsarguments[1]); },
  coefBuffer: function () { return __buffer(jsarguments[2]); },
  newDict: function (name) { return new Dict(name); },
  newTask: function (fn) { return new Task(fn); },
  outlet: function (i, atoms) { outlet(i, atoms); },
  post: function (message) { post(message + "\\n"); },
  random: function () { return Math.random(); }
});
function loaded() { __p.loaded(); }
function liveid(id) { __p.liveid(id); }
function storedkey(value) { __p.storedkey(value === undefined ? 0 : value); }
function who() { __p.who(); }
function listen(key, pass, on) { __p.listen(key, pass, on); }
function rekey(liveId, newKey) { __p.rekey(liveId, newKey); }
// Everything on openflow-probe-in reaches every probe; what isn't ours is dropped.
function anything() {}
`;

const script =
  '// Generated by tools/build-probe.ts from probe/src. Do not edit.\n' +
  bundle.outputFiles[0].text +
  TAIL;
fs.writeFileSync(path.join(outDir, 'probe.js'), script);

// ---------------------------------------------------------------------------
// The patcher
// ---------------------------------------------------------------------------

let n = 0;
type Box = { box: Record<string, unknown> };
type Line = { patchline: { destination: [string, number]; source: [string, number] } };
const boxes: Box[] = [];
const lines: Line[] = [];

function box(
  maxclass: string,
  text: string | null,
  rect: number[],
  extra: Record<string, unknown> = {},
): string {
  const id = `obj-${++n}`;
  boxes.push({
    box: { id, maxclass, patching_rect: rect, ...(text !== null ? { text } : {}), ...extra },
  });
  return id;
}

const obj = (
  text: string,
  rect: number[],
  ins: number,
  outs: number,
  extra: Record<string, unknown> = {},
) =>
  box('newobj', text, rect, {
    numinlets: ins,
    numoutlets: outs,
    outlettype: Array(outs).fill(''),
    ...extra,
  });

const msg = (text: string, rect: number[]) =>
  box('message', text, rect, { numinlets: 2, numoutlets: 1, outlettype: [''] });

const comment = (text: string, rect: number[]) =>
  box('comment', text, rect, { numinlets: 1, numoutlets: 0, fontsize: 10.0 });

const connect = (src: string, outlet: number, dst: string, inlet: number) =>
  lines.push({ patchline: { destination: [dst, inlet], source: [src, outlet] } });

// --- audio and gen~ -------------------------------------------------------

/**
 * gen~ with its codebox embedded. `@stats` and `@coef` are gen~ attributes
 * named after the codebox's two `Buffer`s; setting one rebinds that Buffer to
 * the named buffer~ (Max's gen overview, "Data and Buffer"). That is how a
 * per-device `---` name reaches code that can't contain one.
 */
function genBox(rect: number[]): string {
  let g = 0;
  const gBoxes: Box[] = [];
  const gLines: Line[] = [];
  const gid = () => `gen-${++g}`;
  const gObj = (text: string, r: number[], ins: number, outs: number) => {
    const id = gid();
    gBoxes.push({
      box: { id, maxclass: 'newobj', text, patching_rect: r, numinlets: ins, numoutlets: outs, outlettype: Array(outs).fill('') },
    });
    return id;
  };
  const in1 = gObj('in 1', [20, 20, 30, 22], 0, 1);
  const in2 = gObj('in 2', [300, 20, 30, 22], 0, 1);
  const code = gid();
  gBoxes.push({
    box: {
      id: code,
      maxclass: 'codebox',
      code: genCode(),
      fontface: 0,
      fontname: '<Monospaced>',
      fontsize: 12.0,
      numinlets: 2,
      numoutlets: 2,
      outlettype: ['', ''],
      patching_rect: [20, 60, 700, 600],
    },
  });
  const out1 = gObj('out 1', [20, 680, 37, 22], 1, 0);
  const out2 = gObj('out 2', [300, 680, 37, 22], 1, 0);
  const gl = (s: string, o: number, d: string, i: number) =>
    gLines.push({ patchline: { destination: [d, i], source: [s, o] } });
  gl(in1, 0, code, 0);
  gl(in2, 0, code, 1);
  gl(code, 0, out1, 0);
  gl(code, 1, out2, 0);

  return obj(`gen~ @${GEN_STATS} ${STATS_BUF} @${GEN_COEF} ${COEF_BUF}`, rect, 2, 2, {
    outlettype: ['signal', 'signal'],
    patcher: {
      fileversion: 1,
      appversion: { major: 9, minor: 1, revision: 4, architecture: 'x64', modernui: 1 },
      classnamespace: 'dsp.gen',
      rect: [100, 100, 760, 740],
      bglocked: 0,
      openinpresentation: 0,
      default_fontsize: 12.0,
      default_fontface: 0,
      default_fontname: 'Arial',
      gridonopen: 1,
      gridsize: [15.0, 15.0],
      gridsnaponopen: 1,
      objectsnaponopen: 1,
      statusbarvisible: 2,
      toolbarvisible: 1,
      boxanimatetime: 200,
      enablehscroll: 1,
      enablevscroll: 1,
      description: '',
      digest: '',
      tags: '',
      style: '',
      subpatcher_template: '',
      boxes: gBoxes,
      lines: gLines,
    },
  });
}

comment('audio passes straight through gen~ — it only measures', [20, 20, 360, 20]);
const pluginIn = obj('plugin~', [20, 44, 62, 22], 2, 2, { outlettype: ['signal', 'signal'] });
const gen = genBox([20, 90, 420, 22]);
const pluginOut = obj('plugout~', [20, 136, 68, 22], 2, 2, { outlettype: ['signal', 'signal'] });
connect(pluginIn, 0, gen, 0);
connect(pluginIn, 1, gen, 1);
connect(gen, 0, pluginOut, 0);
connect(gen, 1, pluginOut, 1);

// The two buffer~s gen~ and v8 share. Sized in ms, so at any rate Live runs
// (≥ 44.1 kHz) they hold more frames than the layout needs.
const bufferMs = (frames: number) => Math.ceil((frames / 44100) * 1000) + 10;
comment('the stats ring and the coefficients — layout in probe/src/layout.ts', [20, 180, 400, 20]);
obj(`buffer~ ${STATS_BUF} ${bufferMs(STATS_FRAMES)} 1`, [20, 204, 260, 22], 1, 2, {
  outlettype: ['float', 'bang'],
});
obj(`buffer~ ${COEF_BUF} ${bufferMs(COEF_FRAMES)} 1`, [20, 236, 260, 22], 1, 2, {
  outlettype: ['float', 'bang'],
});

// --- the script -----------------------------------------------------------

comment('identity, the bridge protocol, the report (v8)', [460, 20, 300, 20]);
const thisdevice = obj('live.thisdevice', [460, 44, 110, 22], 1, 3);
// Right to left: the liveId, then the stored key, then `loaded`, so the script
// can say hello the moment it's told the device is ready.
const order = obj('t b b b', [460, 76, 60, 22], 1, 3);
connect(thisdevice, 0, order, 0);

// live.path is the one LOM read this device makes: its own id, so the bridge can
// tell which probe sits where. Banged with the path as its argument, it answers
// `id N` from the left outlet.
const livePath = obj('live.path this_device', [620, 108, 130, 22], 1, 3);
const routeId = obj('route id', [620, 140, 60, 22], 1, 2);
const prependLiveId = obj('prepend liveid', [620, 172, 90, 22], 1, 1);
connect(order, 2, livePath, 0);
connect(livePath, 0, routeId, 0);
connect(routeId, 0, prependLiveId, 0);

// The key, stored in the set. A Blob parameter (type 3) registered in the
// patcher's `parameters` map and Stored Only, exactly as SessionBridge stores
// its state — see tools/README.md. `0` is the new-device sentinel.
const keyPattr = obj('pattr openflow-probe-key', [540, 220, 150, 22], 1, 3, {
  varname: 'openflow-probe-key',
  restore: [0.0],
  saved_object_attributes: { parameter_enable: 1 },
  saved_attribute_attributes: {
    valueof: {
      parameter_steps: 0,
      parameter_exponent: 1.0,
      parameter_invisible: 1,
      parameter_unitstyle: 10,
      parameter_annotation_name: '',
      parameter_mmax: 127.0,
      parameter_mmin: 0.0,
      parameter_type: 3,
      parameter_initial_enable: 0,
      parameter_shortname: 'openflow-probe-key',
      parameter_modmax: 127.0,
      parameter_longname: 'openflow-probe-key',
      parameter_modmin: 0.0,
      parameter_linknames: 0,
      parameter_modmode: 0,
      parameter_info: 'This probe’s identity in the set',
      parameter_units: '',
      parameter_order: 0,
      parameter_defer: 0,
      parameter_speedlim: 0.0,
    },
  },
});
const prependStored = obj('prepend storedkey', [540, 252, 110, 22], 1, 1);
connect(order, 1, keyPattr, 0);
connect(keyPattr, 0, prependStored, 0);

const msgLoaded = msg('loaded', [460, 108, 50, 22]);
connect(order, 0, msgLoaded, 0);

const rIn = obj(`r ${PROBE_IN}`, [460, 140, 130, 22], 0, 1);
const v8 = obj(`v8 probe.js ${STATS_BUF} ${COEF_BUF}`, [460, 300, 320, 22], 1, 5);
const sOut = obj(`s ${PROBE_OUT}`, [460, 400, 130, 22], 1, 0);
connect(msgLoaded, 0, v8, 0);
connect(prependLiveId, 0, v8, 0);
connect(prependStored, 0, v8, 0);
connect(rIn, 0, v8, 0);
connect(v8, 0, sOut, 0);
connect(v8, 1, gen, 0); // epoch / listen / coefgen
connect(v8, 2, keyPattr, 0); // store a new key; pattr's echo is ignored by the script

// `bye <key> <liveId>` on unload. freebang fires as the device is freed, when
// the script may already be gone, so the script keeps this box primed with
// `set bye <key> <liveId>` and the patch sends it on its own.
const msgBye = msg('', [640, 360, 170, 22]);
const freebang = obj('freebang', [640, 330, 60, 22], 0, 1);
connect(v8, 3, msgBye, 0);
connect(freebang, 0, msgBye, 0);
connect(msgBye, 0, sOut, 0);

// --- presentation ---------------------------------------------------------

const pres = (r: number[]) => ({ presentation: 1, presentation_rect: r });
const LIVE_FONT = 'Ableton Sans Medium';
const LCD_BG = [0.156863, 0.156863, 0.156863, 1.0];
const LCD_TITLE = [0.807843, 0.807843, 0.807843, 1.0];
const LCD_DIM = [0.54902, 0.54902, 0.54902, 1.0];

/** Text on the display panel — a plain `comment` bound to the live_lcd_* family (tools/README.md). */
const lcdText = (text: string, rect: number[], presRect: number[], tone: 'title' | 'dim') =>
  box('comment', text, rect, {
    numinlets: 1,
    numoutlets: 0,
    fontname: LIVE_FONT,
    fontsize: tone === 'title' ? 12.0 : 9.5,
    textcolor: tone === 'title' ? LCD_TITLE : LCD_DIM,
    saved_attribute_attributes: {
      textcolor: {
        expression: `themecolor.${tone === 'title' ? 'live_lcd_title' : 'live_lcd_control_fg_zombie'}`,
      },
    },
    ...pres(presRect),
  });

box('panel', null, [820, 380, DEVICE_W, DEVICE_H], {
  numinlets: 1,
  numoutlets: 0,
  mode: 0,
  background: 1,
  rounded: 4,
  bgcolor: LCD_BG,
  saved_attribute_attributes: { bgfillcolor: { expression: 'themecolor.live_lcd_bg' } },
  ...pres([0, 0, DEVICE_W, DEVICE_H]),
});
lcdText('Status', [830, 390, 100, 16], [10, 10, 100, 16], 'dim');
const status = lcdText('Idle', [830, 410, 130, 20], [10, 28, 130, 20], 'title');
lcdText('open[flow] measures here', [830, 520, 130, 16], [10, 143, 130, 16], 'dim');
connect(v8, 4, status, 0);

// --- patcher ----------------------------------------------------------------

const patcher = {
  patcher: {
    fileversion: 1,
    appversion: { major: 9, minor: 1, revision: 4, architecture: 'x64', modernui: 1 },
    classnamespace: 'box',
    rect: [80, 100, DEVICE_W, DEVICE_H],
    bglocked: 0,
    openinpresentation: 1,
    default_fontsize: 12.0,
    default_fontface: 0,
    default_fontname: 'Arial',
    gridonopen: 1,
    gridsize: [15.0, 15.0],
    gridsnaponopen: 1,
    objectsnaponopen: 1,
    statusbarvisible: 2,
    toolbarvisible: 1,
    lefttoolbarpinned: 0,
    toptoolbarpinned: 0,
    righttoolbarpinned: 0,
    bottomtoolbarpinned: 0,
    toolbars_unpinned_last_save: 0,
    tallnewobj: 0,
    boxanimatetime: 200,
    enablehscroll: 1,
    enablevscroll: 1,
    devicewidth: DEVICE_W,
    description: DESCRIPTION,
    digest: TITLE,
    tags: 'open[flow] meter loudness analysis',
    style: '',
    subpatcher_template: '',
    assistshowspatchername: 0,
    boxes,
    lines,
    parameters: {
      [keyPattr]: ['openflow-probe-key', 'openflow-probe-key', 0],
    },
    dependency_cache: [],
    autosave: 0,
  },
};

fs.writeFileSync(path.join(outDir, `${DEVICE}.maxpat`), JSON.stringify(patcher, null, '\t'));
fs.writeFileSync(path.join(outDir, `${DEVICE}.amxd`), pack(patcher, 'audio'));
console.log(
  `built probe/${DEVICE}.amxd — ${boxes.length} boxes, ${lines.length} lines; ` +
    `probe.js ${(Buffer.byteLength(script) / 1024).toFixed(0)} kB`,
);
